# Generated by Django 3.0.3 on 2020-02-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200227_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='No_Ofensivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='ofensivo',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
