# Generated by Django 3.0.3 on 2020-03-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200227_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='No_Ofensivo',
            new_name='total',
        ),
    ]
